### ISSUE TITLE
404 - Not found when entered directly into the browser 

### ISSUE THREAD

**Issue by vikrun** [jonashackt/spring-boot-vuejs#41]
When I enter the main page it works fine and go into another page it works fine.
But if I enter the another webpage in the url, it dont works. I get a 404 from Spring.
The problem is on the server side. I need to configure this.

I am building a Vue.JS & Spring Boot app which I am running through a docker container. The dist folder for Vue is copied to resources/public path and served through the Spring Boot service.

I have set up routes using vue router, but all of these routes return 404 - Not found when entered directly into the browser (but work fine when accesses through the Vue app).

What is the best solution to fix this? Should I create a .htacccess file?

**Comment by vikrun** [comment]
Never mind. I had to create a redirect controller.

/* Redirects all routes to FrontEnd except: '/', '/index.html', '/api', '/api/**' */
    @RequestMapping(value = "{_:^(?!index\\.html|api).*$}")
    public String redirectApi() {
        return "forward:/";
    }

**Comment by renanleandrof** [comment]
I think this should be reopened and added to the sample code!

**Comment by jonashackt** [comment]
@vikrun @renanleandrof  You're absolutely right - since we use `mode: history` (see [Vue.js docs](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations)) now, we also need to forward every other request to the frontend again. Fixing this soon.

**Comment by jonashackt** [comment]
Should be fixed now, please have a look @vikrun @renanleandrof :octocat:

**Comment by Harpner** [comment]
I tried it today and the redirect is not working, still showing the 404 using current version of master. How should this be fixed?

**Comment by renanleandrof** [comment]
Yeah, same here. Tried that and got 404:

https://spring-boot-vuejs.herokuapp.com/callservice

=/

**Comment by achilleas01** [comment]
try to add another Controller
package de.jonashackt.springbootvuejs.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;

@Controller
public class OtherController {

  @GetMapping(value = "{_:^(?!index\\.html|api).$}")
  public String entry() {
    return "index";
  }

}

**Comment by dckristiono** [comment]
you just create new controller file, example: ForwardController.java
This example I want to path /about can forward to /about in vue.

`@RestController()
@RequestMapping("/")
public class ForwardController {

    @RequestMapping(value = "about")
    public ModelAndView redirectApi() {
        return new ModelAndView("index.html");
    }

}`

**Comment by tankchintan** [comment]
@jonashackt This issue should be fixed by #79

**Comment by ferroblesh** [comment]
Looks still not working. It looks the fix #79 didn't work because it's attached to the requestmapping /api
Anything outside /api will return a 404. I think manage this on a separate controller looks better like @velaan suggest it

**Comment by rachitpant** [comment]
I am able to redirect to the home page , but still haven't figured out a way to give control back to vue controller.

**Comment by AdrianLeeElder** [comment]
I think the current code only works for single-level request forwarding. For example:
`/videos` would work but `/videos/5` would not. 

Was able to get the second level working using:
`@RequestMapping("{?:(?:(?!api|static|\\.).)*}/**")`
but is there a way to not have to keep doing `/**` to continuously support more levels?

**Comment by isneezy** [comment]
@AdrianLeeElder have you checked https://github.com/jonashackt/spring-boot-vuejs/pull/92? It should fix this issue for good.

**Comment by AdrianLeeElder** [comment]
> @AdrianLeeElder have you checked #92? It should fix this issue for good.

That seems to be working perfectly! A small optimization would be to move the pattern into a static field so we're not recompiling the pattern on each request.
